library("ggplot2")
setwd("D:/R/Class/Exploratory Data Analysis/xassessment")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
png("plot5.png")
baltimoreMotor <- subset(NEI, NEI$fips == "24510" & NEI$type == "ON-ROAD")
baltimoreMotorAGG <- aggregate(Emissions ~ year, baltimoreMotor, sum)
plot(baltimoreMotorAGG$year,baltimoreMotorAGG$Emissions,type="b")
dev.off()
