setwd("D:/R/Class/Exploratory Data Analysis/xassessment")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
baltimore <- subset(NEI,fips==24510)
png("plot2.png")
em <- tapply(baltimore$Emissions,baltimore$year,sum)
plot(unique(baltimore$year),em,type="b",xlab="Year",ylab="Emissions")
title("The Emissions plot based on Years for Baltimore")
dev.off()
